name: Build and Deploy on Release
 
on:
  push:
    types:
      - published
 
jobs:
  build:
    name: Build and Deploy React Native App
    runs-on: ubuntu-latest
 
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
 
      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Replace with the Node.js version your project requires
 
      # Install dependencies
      - name: Install dependencies
        run: yarn install
 
      # Build Android
      - name: Build Android
        run: |
          cd android
          ./gradlew assembleRelease
 
      # Upload Android APK
      - name: Upload Android APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: android/app/build/outputs/apk/release/*.apk
 
      # Setup Fastlane for iOS
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Replace with your required Ruby version
          bundler-cache: true
 
      - name: Install Fastlane
        run: gem install fastlane
 
      # Build iOS build
      - name: Build iOS
        run: |
          cd ios
          fastlane build
 
      # Upload iOS artifacts
      - name: Upload iOS IPA
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: ios/build/**/*.ipa